import { TextEdit, Palette, VerticalBox, HorizontalBox, Button } from "std-widgets.slint";
export component Console inherits Rectangle{
    in-out property <string> logs: "hello";
    preferred-width: 200px;
    preferred-height: 200px;

    callback log_info(string);

    log_info(msg) => {
        root.logs = logs + "\n" + msg;
    }

    VerticalBox {
        padding: 0px;
        text_edit := TextEdit {
            read-only: true;
            text: logs;
        }
    }
    
}