import { TextEdit, Palette, VerticalBox, HorizontalBox, Button } from "std-widgets.slint";
import { IconButton } from "icon_button.slint";
import { Icons } from "styling.slint";
export component Console inherits Rectangle{
    in-out property <string> logs: "hello zedibox!\n";
    preferred-width: 200px;
    preferred-height: 200px;

    callback log_info(string);

    log_info(msg) => {
        root.logs = logs + msg;
    }

    VerticalBox {
        padding: 0px;
        HorizontalBox {
            padding: 0px;
            Rectangle {}
            IconButton {
                icon: Icons.text_clear;
                clicked => {
                    root.logs = "";
                }
            }
        }
        text_edit := TextEdit {
            read-only: true;
            text: logs;
        }
    }
    
}